opencomponents/base-templates

package.json
src/__snapshots__/getInfo.spec.js.snap
src/getInfo.js
src/getInfo.spec.js

Get info now provide externals as an array of ordered external dependencies.
Template type is now aligned with template name, making it unique

[MAJOR][GPT-525] externals API

---

.travis.yml
README.md
package.json

💥 https://codecov.io/gh/opencomponents/base-templates/pull/26/tree?path=packages pretty nice!

test codecov

---

packages/oc-server-compiler/package.json
packages/oc-template-handlebars-compiler/package.json
packages/oc-template-jade-compiler/package.json

affects: oc-server-compiler, oc-template-handlebars-compiler, oc-template-jade-compiler

fix(dependencies): fixed wrong dependencies

---

packages/oc-template-jade/index.js
packages/oc-template-jade/jade-runtime.js
packages/oc-template-jade/package.json

fix: remove jade-legacy dependency

---

packages/oc-template-jade/package.json

fix: add file inside npm package

---

packages/oc-template-jade/jade-runtime.js

affects: oc-template-jade
This is to make this green https://github.com/opencomponents/oc-client-node/pull/33
💩

fix: make node4 happy

---

packages/oc-template-handlebars-compiler/package.json
packages/oc-template-jade-compiler/package.json

affects: oc-template-handlebars-compiler, oc-template-jade-compiler

fix: commitizen fix :(

---

.travis.yml
lerna.json
package.json
packages/oc-server-compiler/package.json
packages/oc-server-compiler/test/__snapshots__/compileServer.test.js.snap

(updated to latest lerna, added scripts, and updated oc-server-compiler deps for it to be published)

[DX-164] Temporary disabled semantic-release

---

dependencies.yml
package.json

WIP: trying to make dependencies work

---

dependencies.yml
package.json

WIP: using generic js-npm connectors/actors instead of lerna ones

---

dependencies.yml

settings seems to brake actor

---

packages/oc-minify-file/package.json
packages/oc-statics-compiler/package.json
packages/oc-template-handlebars-compiler/package.json
packages/oc-template-handlebars/package.json
packages/oc-template-jade-compiler/package.json

this is because lerna publish failed before due to me not having access to all the repos.

Attempt to manual fix

---

dependencies.yml
packages/oc-template-jade/package.json

This should make dependnecies.io also PR to change the externals. 
Also added the jade-legacy dependencies so that we get notified when a new release happen

[DX-307] Updated dependencies.io

---

dependencies.yml

This should fix the find-replace actor as per https://github.com/opencomponents/oc-template-react/pull/93/files

Fixed find-replace actor config

---

packages/oc-server-compiler/test/__snapshots__/compileServer.test.js.snap
packages/oc-template-handlebars-compiler/test/__snapshots__/compile.test.js.snap
packages/oc-template-jade-compiler/test/__snapshots__/compile.test.js.snap
packages/oc-webpack/lib/configurator/index.js
packages/oc-webpack/test/__snapshots__/oc-webpack.test.js.snap
packages/oc-webpack/test/oc-webpack.test.js

[DX-318]Updated webpack configurator

---

packages/oc-generic-template-compiler/lib/createCompile.js
packages/oc-server-compiler/index.js
packages/oc-server-compiler/test/compileServer.test.js
packages/oc-template-handlebars-compiler/test/__snapshots__/compile.test.js.snap
packages/oc-template-handlebars-compiler/test/compile.test.js
packages/oc-template-jade-compiler/lib/compile.js
packages/oc-template-jade-compiler/test/compile.test.js
packages/oc-webpack/lib/configurator/index.js
packages/oc-webpack/test/__snapshots__/oc-webpack.test.js.snap
packages/oc-webpack/test/oc-webpack.test.js

[DX-385] Add sourcemaps to server.js compilation when production=false

---

acceptance-setup/__tests__/__snapshots__/acceptance.js.snap
acceptance-setup/__tests__/acceptance.js
acceptance-setup/server.js
package.json
packages/oc-webpack/test/__snapshots__/oc-webpack.test.js.snap
yarn.lock

There must be something wrong related with the publish that made some tests red.
Closes #277 
Closes #276 
Closes #273

[DX-463] Fix master branch

---

acceptance-setup/__tests__/__snapshots__/acceptance.js.snap
acceptance-setup/__tests__/acceptance.js

We forgot to replace the version in this particular test.

Fix snapshots

---

packages/oc-template-handlebars/package.json

https://nodesecurity.io/advisories/755

handlebars Open CVE

---

packages/oc-template-handlebars-compiler/package.json
packages/oc-template-handlebars/package.json
packages/oc-template-handlebars/test/__snapshots__/getInfo.test.js.snap

/cc @kmcrawford I found some more handlebars references to upgrade. Can you review?

More handlebars upgrades

---

packages/oc-template-handlebars/package.json
packages/oc-template-handlebars/test/__snapshots__/getInfo.test.js.snap

Reverts opencomponents/base-templates#441

"Update handlebars in packages/oc-template-handlebars/package.json from 4.0.13 to 4.1.1"

---

packages/infinite-loop-loader/package.json
packages/oc-empty-response-handler/package.json
packages/oc-external-dependencies-handler/package.json
packages/oc-generic-template-compiler/package.json
packages/oc-generic-template-renderer/package.json
packages/oc-get-unix-utc-timestamp/package.json
packages/oc-hash-builder/package.json
packages/oc-minify-file/package.json
packages/oc-server-compiler/package.json
packages/oc-templates-messages/package.json
packages/oc-view-wrapper/package.json

So they will get published to NPM

add d.ts declaration file to package.json/files field

---

lerna.json
packages/oc-server-compiler/index.d.ts
packages/oc-server-compiler/package.json
packages/oc-statics-compiler/index.d.ts
packages/oc-statics-compiler/package.json
packages/oc-template-es6-compiler/index.d.ts
packages/oc-template-es6-compiler/package.json
packages/oc-template-es6/index.d.ts
packages/oc-template-es6/package.json
packages/oc-template-handlebars-compiler/index.d.ts
packages/oc-template-handlebars-compiler/package.json
packages/oc-template-handlebars/index.d.ts
packages/oc-template-handlebars/package.json
packages/oc-template-jade-compiler/index.d.ts
packages/oc-template-jade-compiler/package.json
packages/oc-template-jade/index.d.ts
packages/oc-template-jade/package.json

Add TypeScript types for all templates renderers/compilers, server-compiler and statics-compiler

add types for templates renderers and compilers
